### ISSUE TITLE
`send_invoice` fails with `Faraday::ParsingError`

### ISSUE THREAD

**Issue by suweller** [maartenvanvliet/moneybird#19]
According to the Moneybird documentation:
https://developer.moneybird.com/api/sales_invoices/#patch_sales_invoices_id_send_invoice
> RESPONSE
> Status: 200 OK
> Body: 200

Backtrace:
```
Faraday::ParsingError:
  784: unexpected token at '200'
# json-1.8.6/lib/json/common.rb:155:in `parse'
# json-1.8.6/lib/json/common.rb:155:in `parse'
# faraday_middleware-0.12.2/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
# faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:51:in `parse'
# faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:40:in `process_response'
# faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:33:in `block in call'
# faraday-0.14.0/lib/faraday/response.rb:61:in `on_complete'
# faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
# faraday-0.14.0/lib/faraday/request/url_encoded.rb:15:in `call'
# faraday-0.14.0/lib/faraday/rack_builder.rb:143:in `build_response'
# faraday-0.14.0/lib/faraday/connection.rb:387:in `run_request'
# faraday-0.14.0/lib/faraday/connection.rb:175:in `patch'
# moneybird-0.9.6/lib/moneybird/client.rb:41:in `public_send'
# moneybird-0.9.6/lib/moneybird/client.rb:41:in `block (2 levels) in <class:Client>'
# moneybird-0.9.6/lib/moneybird/traits/send_invoice.rb:9:in `send_invoice'
```

I've quick-fixed it by doing the following in my code:
```ruby
invoice.class # => Moneybird::Resource::SalesInvoice
begin
  invoice.send_invoice
rescue Faraday::ParsingError => ex
  raise unless ex.message == "784: unexpected token at '200'"
end
```

**Comment by jankeesvw** [comment]
I think this issue can be closed, they probably changed something on the MoneyBird side. Or it could be related to your contact not having an email address, when I do the following I also get a Faraday error:

```ruby
client = Moneybird::Client.new("secret")

administration = administrations.first
contact = administration.contacts.create(company_name: "ACME", firstname: "Foo", lastname: "Bar")
invoice = administration.sales_invoices.create(
  reference: "test",
  contact_id: contact.id,
  currency: "EUR",
  details: [{ description: "Testing", price: 10 }]
)

invoice.send_invoice

# Traceback (most recent call last):
#     1: from (irb):25
# Moneybird::HttpError::UnprocessableEntity (#<struct Faraday::Env method=:patch,
# body="{\"error\":{\"email_address\":[\"cannot be empty\"]}}", url=#<URI::HTTPS ....
```


When I add an email address to the contact it works just fine.

**Comment by maartenvanvliet** [comment]
Thanks for checking!
